# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  #- osx

julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

codecov: true
coveralls: true

jobs:
    include:
        - stage: "Documentation"
          julia: 1.3
          os: linux
          script:
              - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                                     Pkg.instantiate()'
              - julia --project=docs/ docs/make.jl
          after_success: skip
